CREATE SEQUENCE  "LAB2_ZV_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 4 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_EMPLOYEE_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 4 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 3 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_PROJECT_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 3 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_REQUIREMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 3 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_LOCATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 3 CACHE 20;
--
CREATE SEQUENCE  "LAB2_ZV_JOB_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 4 CACHE 20;

--USER
CREATE TABLE "LAB2_ZV_USER"
(	 "EMPLOYEE_ID" NUMBER NOT NULL,
      "USERNAME" VARCHAR2(50 BYTE) NOT NULL,
      "PASSWORD" VARCHAR2(50 BYTE) NOT NULL,
      "ROLE" VARCHAR2(50 BYTE) NOT NULL,
      "ENABLE" NUMBER NOT NULL,
      CONSTRAINT "LAB2_ZV_USER_PK" PRIMARY KEY ("EMPLOYEE_ID")
);
--EMPLOYEE
CREATE TABLE "LAB2_ZV_EMPLOYEE"
(	 "EMPLOYEE_ID" NUMBER NOT NULL,
      "FIRSTNAME" VARCHAR2(50 BYTE) NOT NULL,
      "LASTNAME" VARCHAR2(50 BYTE) NOT NULL,
      "PROJECT_ID" NUMBER,
      "JOB_ID" NUMBER,
      "SALARY" NUMBER,
      CONSTRAINT "LAB2_ZV_EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
);
--PROJECT
CREATE TABLE "LAB2_ZV_PROJECT"
(	"PROJECT_ID" NUMBER NOT NULL,
     "PROJECT_NAME" VARCHAR2(50 BYTE) NOT NULL,
     "BUDGET" NUMBER NOT NULL,
     "LOCATION_ID" NUMBER,
     "CUSTOMER_ID" NUMBER,
     "REQUIREMENTS_ID" NUMBER,
     "TIME_TO_BUILD" NUMBER,
     CONSTRAINT "LAB2_ZV_PROJECT_PK" PRIMARY KEY ("PROJECT_ID")
);
--CUSTOMER
CREATE TABLE "LAB2_ZV_CUSTOMER"
(	"CUSTOMER_ID" NUMBER NOT NULL,
     "COMPANY_NAME" VARCHAR2(50 BYTE) NOT NULL,
     "COMPANY_BUDGET" NUMBER,
     CONSTRAINT "LAB2_ZV_CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
);
--LOCATION
CREATE TABLE "LAB2_ZV_LOCATION"
(	"LOCATION_ID" NUMBER NOT NULL,
     "CITY" VARCHAR2(50 BYTE) NOT NULL,
     "ADDRESS" VARCHAR2(50 BYTE) NOT NULL,
     "AREA" NUMBER,
     "PERMISSION" VARCHAR2(50 BYTE) NOT NULL,
     CONSTRAINT "LAB2_ZV_LOCATION_PK" PRIMARY KEY ("LOCATION_ID")
);
--REQUIREMENTS
CREATE TABLE "LAB2_ZV_REQUIREMENTS"
(	"REQUIREMENTS_ID" NUMBER NOT NULL,
     "MATERIAL" VARCHAR2(50 BYTE) NOT NULL,
     "COLOR" VARCHAR2(50 BYTE) NOT NULL,
     "TYPE" VARCHAR2(50 BYTE) NOT NULL,
     "FLOORS_COUNT" NUMBER,
     CONSTRAINT "LAB2_ZV_REQUIREMENTS_PK" PRIMARY KEY ("REQUIREMENTS_ID")
);
--JOB
CREATE TABLE "LAB2_ZV_JOB"
(	"JOB_ID" NUMBER NOT NULL,
     "JOB_NAME" VARCHAR2(50 BYTE) NOT NULL,
     "JOB_BASE_SALARY" NUMBER,
     "JOB_PREMIUM" NUMBER,
     CONSTRAINT "LAB2_ZV_JOB_PK" PRIMARY KEY ("JOB_ID")
);
------------
ALTER TABLE "LAB2_ZV_EMPLOYEE" ADD CONSTRAINT "LAB2_ZV_EMPLOYEE_FK1" FOREIGN KEY ("JOB_ID")
    REFERENCES "LAB2_ZV_JOB" ("JOB_ID") ON DELETE SET NULL ENABLE;
--
ALTER TABLE "LAB2_ZV_EMPLOYEE" ADD CONSTRAINT "LAB2_ZV_EMPLOYEE_FK2" FOREIGN KEY ("PROJECT_ID")
    REFERENCES "LAB2_ZV_PROJECT" ("PROJECT_ID") ON DELETE SET NULL ENABLE;
--
ALTER TABLE "LAB2_ZV_PROJECT" ADD CONSTRAINT "LAB2_ZV_PROJECT_FK1" FOREIGN KEY ("LOCATION_ID")
    REFERENCES "LAB2_ZV_LOCATION" ("LOCATION_ID") ON DELETE SET NULL ENABLE;
--
ALTER TABLE "LAB2_ZV_PROJECT" ADD CONSTRAINT "LAB2_ZV_PROJECT_FK2" FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "LAB2_ZV_CUSTOMER" ("CUSTOMER_ID") ON DELETE SET NULL ENABLE;
--
ALTER TABLE "LAB2_ZV_PROJECT" ADD CONSTRAINT "LAB2_ZV_PROJECT_FK3" FOREIGN KEY ("REQUIREMENTS_ID")
    REFERENCES "LAB2_ZV_REQUIREMENTS" ("REQUIREMENTS_ID") ON DELETE SET NULL ENABLE;
----------------